// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright © 2026 Ryan Tenney.
//
// GENERATED FILE - DO NOT EDIT BY HAND.
// Regenerate with: python3 scripts/generate-map-data.py
//
// World landmass outlines from Natural Earth 1:110m (public domain),
// simplified and polyline-encoded at 0.1 degree precision.
// 114 rings, 3071 points.

import CoreGraphics

enum WorldMapData {

    /// Decoded landmass rings. Each ring is a closed polygon of
    /// (longitude, latitude) pairs in degrees.
    static let landRings: [[CGPoint]] = encodedRings.split(separator: "\n").map { decodePolyline(String($0)) }

    /// Decodes one Google-encoded polyline (precision 1, i.e. 0.1 degrees)
    /// into (longitude, latitude) points.
    private static func decodePolyline(_ text: String) -> [CGPoint] {
        var points = [CGPoint]()
        var lat = 0
        var lon = 0
        var index = text.startIndex

        while index < text.endIndex {
            var deltas = [Int](repeating: 0, count: 2)
            for component in 0 ..< 2 {
                var shift = 0
                var result = 0
                while true {
                    let byte = Int(text[index].asciiValue ?? 63) - 63
                    index = text.index(after: index)
                    result |= (byte & 0x1F) << shift
                    shift += 5
                    if byte < 0x20 { break }
                }
                deltas[component] = (result & 1) != 0 ? ~(result >> 1) : (result >> 1)
            }
            lat += deltas[0]
            lon += deltas[1]
            points.append(CGPoint(x: Double(lon) / 10.0, y: Double(lat) / 10.0))
        }
        return points
    }

    private static let encodedRings = """
~p@fd@RJAtAKb@@wAOY
tp@nbB@d@Sr@GKBe@Ja@
vo@f[HYJGPCRnC?n@GXGCK{@_@m@Cg@
|l@vjA?q@J\\Gn@GC
|l@nmAF_@G`AEM
|k@z|@@k@HK?zACRGHCK
jk@xi@FCNHDl@?XGIDl@ENG?Ic@?UIEWAIIAQ
bg@rc@BFA^HZLJLID^Tb@FBLQH_@\\[p@UH@LVBXLTPjBFN@bCFEB]Ja@DTA`@DZN@Ts@h@yHN]]gDFkCGKE[As@SaEMVE?BtBGDOA_@iCK_CScBKc@GECTOUM}@Ug@Fy@G?GI@UFE@WEgAFIUaCK[BOASNYOs@?YFGGOAcABk@JUCyAOaBWe@Lm@?SJ[WcASyA@QK_@Cc@GAEQGu@Be@BOHAJ[Lu@?SKa@H_BXOH@Jb@FA?WVVFg@CU[i@OOGiAW]UiA?oAEMMINOBQAyAD_@CmA_@}@XcACoAK]Ce@Ng@?UJ}@OcADoBKwBQEDKVQBQA_DDMFBDKHk@HiA?UEMNq@Bo@Ro@BqBPmAF@^b@L~@Td@LJP@TW@e@HGFfB`@f@\\mAPgBHIBy@FQCw@HoAhB??~_FiB?KQFc@G[F]G]Cy@L{@NqDEy@HeCKkBGCEnCGNCt@WQIBQlAA}AD]SsAGFIt@ErBUv@UDF[CaAFOA_@QgBOFEECYDKWuDByGIgABYIm@R_@ESNiAEu@FuAGIMVAVGJUJD{AL[?[GmA@m@MQFO@o@FOFiAOWFSA[Ja@AYQwBI]QAe@V_@UODu@}A?SWcAAOBK
t`@ji@JYB]HH?REHLTATS|@a@n@XgAWOGS@M
|^pc@FMFBDZEHFNGHMWDQ
`^}j@@^WCH_@
nX{yADSCe@VADFN@EDLLAPm@XI?
pXckBFCGOFCH?^\\HGD^`@PLXGr@EBOISYUk@][ICIM
rUclBRMMADGNCDOCa@\\HANDDHAZRFNGHOIKDGTGAEM[AQFg@`@?GHKDM
zLmgBBFMV_@\\FS
xIonBDEJ@?VI@EG
nIcoBBLG@I[H?
nGi^h@EDBKDDBVABDP@hCl@L`@KZy@LOAAIUIMAg@HWGGe@W[IEG@@Gc@Q
rGwxALEEMNOXAJGh@IZo@B@LKRGCGHGCCTCb@g@NCV?NIdALRFFNt@Z`@DFJ?TVf@KZIAPZOz@KJYFGHARIEMBLHBPa@UM@VZNFGNK?UTCCUz@@b@Ln@ARNd@PH@jATd@AZO^K?EMa@?SHUBcA`@FIQFLOI?[NYGK@MGLAMGUi@?MMe@E_@]YQAQMPGCIIFIEBIMAQOCIE?@GC?ESTY@WKBSQE@KGEKA[I?ENCKLWFa@EWHIPL?DFARLDAh@gADCDQEMSG[Gs@?a@Oh@S
jEmjAK`@CQJQ
~DadBBB]P?E
hEwlA@PQIKUEk@Rj@
`DuhADGAKFCDn@IGAI
`DykAH@D\\AZG?CODK
fC{bA@e@GEFc@LGB]JWFTITIfBGb@IB?PSM@WFW
zBesALHO@MG
fCm`B@DGF[LZ]
lB_~ANb@Kd@EA@[IEHA?KMOK@@O
dAonADDCLGBAS
|@qpANEIN?h@KC
xAu~ADDSFU`@CCLYNO
VyrA^EJUUOKU?Qj@}BRWJCJ_@HE@PLCJQTK?KF?BMBDFUD@Iv@WXOJIXJZNADNC^OPCRDB?XOGEMe@NQd@?NS\\HD@FOBINEc@E@?\\KFCPIFIe@F_@
[gmARNBLCRBp@LBPQGKGc@H?CHJFFPXSDBVQJ?DJEFOIFREBGAKLSADLr@ABJEFQESB?FMDcAWMQFg@?WMS
UmoAN@AHL@HG@De@LWIJA@K
tBcaA?Ta@h@eAp@QN_@L_A~@I@Dk@|@}@?Uf@i@NFFSVI@MLI
c@uhAPU@VLDP?LPp@HE@FTKFGVFVIFA\\Y@EHOHc@?MKDMCOOCG_@c@_@W_@OI?GHIFAJ]F@?LHCFLPJPM
gD_nAVAPDSFHFNEFDKVMDIEGJFDAHJLEBOGMWHEEOIC?MO@HO
{Bwq@BPOF[B_@GHMb@SRB
iE`e@?TMEAK?C
mEolAXRMJWI?KJBQO
yDaiAPXg@c@SINC
mFekADWF?NT
sFmmAVEENPEDHM?ADKB@KG?OJ@Q
eG}jAPBYR@Q
qJyjADKEEL?LENBFJNBNC?SHYXAUVFBKLBPEHKGEDF@KH[BFGq@G
kJ~g@BB@ZI?AQ
eJ`o@BDITEI@QHM
mKjl@Ds@DC?KD@FSFFCXBHCBNLGDCLB\\EJGADa@EGGHG?AJEC
uJ}cAHNENQ@GIEa@FC
}Jd`B?FW?NU
gMxp@FGASXc@BQD@F]FN?v@IMERQJOdACGARNX?PQWG]@a@
{Mlo@@DQJKC?E
gMwjANH_@Ja@[DI
iTcsADCJJEFBHJDEJI?KIBKIG
iUsTHLBAFRAHGB
iUyMDI@i@D@@\\GV
{VuH^FSt@IC
wXwDLKX@?HDFEFc@B@I
eVcwANFHCLHFX@b@TZELO?Bb@HT?VNS^LHJGHQCEJMFESc@k@Eg@BUc@SHM[g@WMWBKGCUZIN?RP
kY_ENFCFMDMQ
sZ}xABMGMTCDZRPM^TH?TSBMIAUk@K
c\\xf@Ba@FPGVEDEG
u]re@Eb@IPB_@
i]dlA@HG`@SXCTODHs@
u^`b@PLGMDKDDFm@LDCMVINHATOCCBPV?JIMCR?z@E@GKCFKO_@SKMEY
w`@|qAASTDNO?FW\\O@
u^wxA`@UE\\ZJTQL?KNLJy@Bi@EQJ[AIQGFCI
u_@fCJb@AZUOSHWi@AQJSLHLC
wa@}FNJKTG@E]
ub@r~AFREHIBI]FU
sc@z@RTAi@NBPP@SXS@M^QBWJ@DHHEHND|@CHHJAPDLCJS]CQC^GDEUIJMC@]KCKLCVEDGGEDHJS?IHSEOO
md@nfB@JGXAc@
{e@pp@JFGLGI
ef@dr@HV?LEBGM?[
{f@hjBH{@DNGV@PAB
ah@ft@HCCIPy@H?AOFMDPE\\GJRn@IF@XIOa@I
qh@`HLBLULXPjAIpAGSIj@Cc@E?Ch@MKA_@L]K]DYI_@
}h@ln@?TIBIGCQDOJ@
sh@jlBDMODBu@Pg@HR@^P@BFKz@IB?j@EHGCBVHIFJoA?b@eB
ej@vz@DLEX@NGZM_@F_@
gk@ooB?TEBGY
ik@tnB@XM?Bo@
mj@pw@R@O[LWLDLQ_@c@UABy@HYHAJNHMH@Ld@@ZETb@\\LV@ZFNJ@BTNXTRNFV@@]`@QC[Fe@Pa@Lm@Bu@N@RETMR]EOUI]HKLG_@MUMKM@QLMVUWo@NEMFu@CQPi@FE?c@h@EBQJOK[]_@`A_ALFTk@Jm@NGBMDGVALZD`@PV?~BLNFXl@r@COY_@Oi@A]HQJPd@KHYCa@USLAFKJVR~@NVALQ@Oc@Bt@DAT|@LJL@HE?GE@BED@LhAC]BE@h@DD@ELBNLKJTGVNMCGHQ@HBJCALDMP?@EXENLDRR`@h@j@Z?|@W`@D?NMHg@VMCIBSVHROX@v@@FPGBR?LKL?j@Zv@PN\\E^Jd@Bb@MXQHGBUHGKo@KWa@IIc@?[LEVN@CVFCHBCb@DJHBOE}@L_@DEL@LDp@Dh@_@BOOc@Rw@OUWCIKA]W_@DMJD@HREHHNG?GOEEFO?GWG@GGLE@MNM?g@FI@OIKAo@DNHE?OHONA?IJULKH??GNSBWCQBSFUVW?Gl@OBILANNDE@c@R?KORy@HIJBEWHe@?]d@w@D_@FGb@I`@FpAfALDd@Aj@FFDXBXRR@HPJBFr@\\z@RPX?\\FHLb@TV^RFVTJTAXIP@LKJH@PYLBFMH@XPH\\@|@d@CDJBTGPDFRADMGIJEP`@\\F?PJNLDLSBSPFJVVJNXTEHK?XJXPBE^Wl@MFKEKHa@@SGOUE\\OQa@EFWi@IELXDCJaAKKIi@FAG}Ac@]DOEW@YK{BO_@@]BIRG@w@xAOFEA}BdAUZGESHMEYYIBHFIJCCQ@CEYKG@KWE@AGOCAIUOEFKCg@BOLKBCCMP@HNPJIDPKB@FGBCTB@EJM@SZH@EJQ?ABCCc@f@AGEB@RMt@a@j@KXHd@]rAMTG^_@f@IBAEQA[Lo@n@GPO?OTMB?JURk@PK`@F@VCdA}@n@Q?ITOFJKDYd@Y@Uj@KJ?IQGSXcAb@SVKh@K@SR_@NWVOBIHa@CODu@K[BYJCAF]PIEE_@H[v@Gb@QJKAIVOBMVI?M\\QBOXQJAp@Y`AKt@@ZQ|@BTLCNhAIBSIEUEDd@bAHMNPLh@FDH\\HD^~BC@Y}@AW_@y@MAKKDVCDFJIJDDIFF^QAGJBXM\\K@GL_@]?]GO?OEMGBCHGMHf@ELB\\EZS`@QgA?OH@?i@e@hAGZIK?c@IWIEGSKy@@QK]D]FOAi@B@B_@FsBCYXmCMi@@]M}@FMCMIERm@M[NAI_@@WNmA@o@HYHZBc@EgAJSIUGRGKAg@Ne@AUHa@C}@KBCQF_@P?OK?OSISl@UAMWJm@T[HP
ul@jfAFHEm@HYIWFQPOGISL?e@FU`@QReAF@@^FKDDGfALpCIJCj@OVGaBAlBGHGm@E`AU]Ku@
{l@h`AJPM\\A_@
ul@tn@D?@~@KZGAAG@m@
wl@bu@LOOQIs@Ta@J@Ky@PgAHAEe@LSFo@FQPQHb@PmAP]?]LDV`@[v@@XJ@Xw@RKLDSjAZq@FAS~AIVEESx@D?Bx@GPMMCmAED]_@GBQd@Eh@CMMTG`@DHBb@EfAGjAGNGS?ZSDQOGSEs@
cm@v}@?{@DEHRF_@PBF`@APU~@E?@i@MT
wl@wxAChAGQAYF[
ol@fy@NTATOJI?M]BoAP\\
sk@hjAHr@GHKl@c@g@KRAcABmALi@RhALX
}m@e}AFTIdAEE
{m@ny@FJEr@IIC[
gn@uyANNBhBMf@KICY?u@
}n@p|@FOJ?LH@^CTI??^M@
sn@rbAFGCe@HCHJBbAFp@?\\EBIi@?tBS[EQFw@Jc@?a@QZGQ@U
ek@}b@AjAGDEb@I@CSK@Og@APQo@IDWoBKkCFMDLPbCR|@d@|@PC
eo@dz@DU?g@FQDDHc@AaDFSFEHh@A|CEr@UHGRI~@GG
oo@rgAL@FNJvACZ[kA
co@{aAHCCS?y@P{@HBTxAFu@CQLIIi@B_AHC@sAMA@iAJ_@JIFJNWF_@SSF_@Ea@Fe@EM@a@QNG[JsDJQNs@AwBFON@DWCiCPc@EWMNGIBgBPuAnA?HXAX^g@FADDCb@NhAZz@FFMZNr@GHHPCZLDRVFABUZ@@RNFFGJ`@TFB\\TDPZwAZ[IKQG?E_@k@eAOc@]O@VPJTr@YNFr@^p@LODhAM?C\\HXAz@D`AtAlC@_@JIBSIK@UT[PARNv@HZ\\LFx@`AJZ?JIJZl@DDL?Tj@J@JQb@WV?HFLr@YASHCOOLCHBFGJKIQAERR~@IIGBKOIJRf@JJ@RHHJKBOH?BOMUF_@JABZTZLHHSRG`@YN?BJJCDK^F@JfAn@`@v@@THJEFFJLn@TF?HMDGEEZRb@PNLBn@a@Z]d@G`@@|@nAKFMEKNAN_@PGP?POC?PT@l@NN??Mb@Kd@q@JGh@ADGVE@L_@h@q@VW@e@^JBK@{@KKFUAIFq@HOFVb@EVYEQBWNECCJOLi@R?PFAJDEXF@Bd@N?HHLZp@x@F?Ld@NDh@EPF`@?@JNFDEDPPNQPo@P[Ne@H[PkBPJZALWXGGEDUd@]RD`BKpAYFAHJb@EVORERk@Z@HELFDAJl@OR[N@TMM@IEAEDEVBJGAk@m@o@\\?LGJe@XUd@XBLX@DTLDDRF?Nx@NBPr@LPL|@JJ@\\s@PAC]Be@ZODOTSLY?UJKRYJq@b@?H[Ed@RON]LVEr@[j@_@NBT[bAKJQh@QdAoAF?DJX[?I_@aCZ@jA\\r@b@XTr@dAf@\\PX`@LFFVHJADK`@Bl@YlAEZLJJPh@j@r@L@^QZBBCNJVn@HEr@LnAnAPl@B@?~@Pz@MV]HCEM?{Az@cBPWPe@NQNm@?m@M]UYA]NKEgAXmA|@i@MCBe@IKFCHQFHr@g@^Bn@ZlAIr@Px@I\\g@n@IRIHUDYZMBKXMH[@UPCGWMg@Gg@BQNQAOMSEOQc@MEK[WAQc@i@YB[IKKQc@a@S?MHK@o@[iAAkAGSBi@IUBMH?GOBAHHH?BEP@HLHC?KLKNiAPITcAMSODGEK[B[FEDa@DE?YLo@KWAQBMHEGCD_@IO}@[O@GCIDGGA\\JL@\\INATFBBLKR?TSJILOIIJQUA]MG@e@Qo@?a@T}@Ai@IWIAKBs@~ACMOOGHG[E?RpAJ?DIASFBLn@CJGCERKUCDC^G?@R^T@NVBTPRGDQBB@VNVKDAVBVJM@H?JIHBBTOBFNSH?CPHE@JPG?LGN]J_@TGJ[AKJWx@MNACOHAJFDEDICANDNN?HEHQNINU?ODEBDXs@FBIJANJHFOH@@HNH@FUGSLWb@I\\W^SDIXXn@Ed@D\\V@LPBX`@TJGFJLBBLLL?l@NRAHQJCRDFAR[AGLi@Mc@BGFM[DyBKIg@C_@b@G\\M@CYDa@WDHQOm@OEMk@]QKo@?OBCIM]LS?KGAQIWNDFKRVPCBUF@I_@L_@UeABSDA?SICE[_@BKIGQNO?O[E@DELK@Gs@@i@IUIRLfBKJERSCQFKGe@mAG@IZD`@LRJC`@fAZLVa@TPDT`@FPHAVNJ?VeAd@KJVf@BZIXcALKQQu@Se@aAuAg@wAIk@@_@O]CiAL}@DXJUESJa@Bu@VkAFOL?HTD^OxABLL_@\\AJi@IAIJEMJo@EOMJSm@Fc@MKKNKIKLDw@JI@VJ?DMC_@KC[oB@OJR@WEMAe@G]JUKWKTGKFy@ZcBIMOTAVGGUJQc@QMCMBu@JCNRDMLEZBJULHZd@@UEGEUIEIQIJMGATIBSOOXMc@MBAIJIRF@UMHGa@?i@Hc@OPS@E}BKNKWMqBCEAu@BOIk@?e@ICGSGo@Da@DZ
yXu]LIDO@NVFBDVEBQHMB]E]g@AENME?LQCDSGOURBNN@QFGEGBEV]R@SM?Aa@_@?Ab@Jh@JHBPRRPQL@
mo@ry@An@CB?g@
qo@zcADd@EZGO@w@
uo@mNHj@Eb@CMGJCi@FG
yo@zz@B\\CNOHH{@
}o@p}@FGIlBESCVG@H}A
}o@u`AFpBYe@AOJaA
yp@mJL_AFp@NHBPNH?VKh@EQE\\Qf@ONEw@DI?[EGA]
gq@{NDg@J\\@x@Cx@CBAZGTE}@B[ES
iq@}^HdACTGK?l@CeADCG]B]
ip@m}@@h@Cv@G`@MNCXMs@Ei@\\uA
yp@ju@FWR~@@b@Ah@ITEAEO?d@O`@M[ASCFAm@JYFaA
}r@xi@HcCB?PrB?k@PnAN`@HpB@[BLHOXvABC?a@B?Jt@Er@?|BI@Cc@MHFaAMXC`@GOCc@EEGZKFBeAG_@?rBGb@Mf@EBG{AG]Fm@KOC}@
es@|ON}BFd@@vDFmCEe@FOHTMsCB{@FKR|A@|@@m@Xf@V?JWF~@He@PC?TPY@j@FWDFBv@LYF?Gf@DHNu@NEB`@Qf@JEJV@qA^jBFpAFRRZLj@HbALPL?JHN^NGb@R@ZQ\\?f@IPSLW`@MHQBQZMGGLWSE]WKJr@EVM@IGB{@Qr@@RENQUi@r@GXG?Kt@?nCQx@G{AK`CGASuCGGEt@GOOcBIHGmB?}@DUIs@LuBIn@GAKcA?eAEY
"""
}
